---
- name: backup
  hosts: all
  become: yes

  tasks:
  - name: install borgbackup
    apt:
      name: borgbackup
      state: latest
      update_cache: yes
  
  - block: #===== configure server =====
    - name: Create user 
      user: 
        name: borg
        create_home: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: create folder
      file:
        path: /home/borg/.ssh/
        state: directory
        recurse: yes
        owner: borg
        group: borg

    - name: Create authorized_keys file on server
      file:
        path: /home/borg/.ssh/authorized_keys
        state: file
        owner: borg
        group: borg

    when: ansible_hostname == "server"

  - block: #===== configure client =====
    - name: Generate an OpenSSH keypair on client
      openssh_keypair: 
        path: /home/vagrant/.ssh

    when: ansible_hostname == "client"