---
- name: backup
  hosts: all
  vars_files: env/env.yml
  become: yes

  tasks:
  - name: install borgbackup
    apt:
      name: borgbackup
      state: latest
      update_cache: yes
  
  - block: #===== configure server =====
    - name: Create user 
      user: 
        name: borg
        create_home: yes
        password: "{{ password | password_hash('sha512')}}"
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: create folder
      file:
        path: /home/borg/.ssh/
        state: directory
        recurse: yes
        owner: borg
        group: borg

    - name: create backup folder
      file:
        path: /backup
        state: directory
        recurse: yes
        owner: borg
        group: borg

    - name: Create authorized_keys file on server
      file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg

    when: ansible_hostname == "server"

  - block: #===== configure client =====
    - name: Generate an OpenSSH keypair on client
      openssh_keypair: 
        path: /home/vagrant/.ssh/id_rsa
        state: present
        group: vagrant
        owner: vagrant


    - name: install sshpass
      apt:
        name: sshpass
        state: latest

    - name: ssh-copy-id
      command: sshpass -p otus2024 ssh-copy-id -i /home/vagrant/.ssh/id_rsa.pub -o StrictHostKeyChecking=no borg@192.168.0.181

    - name: Copy Unit file
      copy: 
        src: borg-backup.service
        dest: /etc/systemd/system/borg-backup.service

    - name: Copy Unit timer
      copy: 
        src: borg-backup.timer
        dest: /etc/systemd/system/borg-backup.timer      
    
    - name: enable unit
      shell: systemctl enable --now borg-backup.timer
    when: ansible_hostname == "client"