---
- name: backup
  hosts: all
  become: yes

  tasks:
  - name: install borgbackup
    apt:
      name: borgbackup
      state: latest
      update_cache: yes
  
  #- block: #===== configure server =====
  #  - name: Create user 
  #    
  #  when: ansible_hostname == "server"